<a href="https://colab.research.google.com/github/PritwishSaha/Crime-Rate-Analysis-Across-Cities/blob/main/Crime_Rate_Analysis_Across_Cities.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
from google.colab import files
a = files.upload()

Saving crime_dataset_india.csv to crime_dataset_india.csv

In [4]:
import pandas as pd
df = pd.read_csv('crime_dataset_india.csv')
df.head()

/usr/local/lib/python3.12/dist-packages/google/colab/_dataframe_summarizer.py:88: UserWarning: Parsing dates in %d-%m-%Y %H:%M format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  cast_date_col = pd.to_datetime(column, errors="coerce")

,Report Number,Date Reported,Date of Occurrence,Time of Occurrence,City,Crime Code,Crime Description,Victim Age,Victim Gender,Weapon Used,Crime Domain,Police Deployed,Case Closed,Date Case Closed
0,1,02-01-2020 00:00,01-01-2020 00:00,01-01-2020 01:11,Ahmedabad,576,IDENTITY THEFT,16,M,Blunt Object,Violent Crime,13,No,NaN
1,2,01-01-2020 19:00,01-01-2020 01:00,01-01-2020 06:26,Chennai,128,HOMICIDE,37,M,Poison,Other Crime,9,No,NaN
2,3,02-01-2020 05:00,01-01-2020 02:00,01-01-2020 14:30,Ludhiana,271,KIDNAPPING,48,F,Blunt Object,Other Crime,15,No,NaN
3,4,01-01-2020 05:00,01-01-2020 03:00,01-01-2020 14:46,Pune,170,BURGLARY,49,F,Firearm,Other Crime,1,Yes,29-04-2020 05:00
4,5,01-01-2020 21:00,01-01-2020 04:00,01-01-2020 16:51,Pune,421,VANDALISM,30,F,Other,Other Crime,18,Yes,08-01-2020 21:00

In [5]:
df.columns

Index(['Report Number', 'Date Reported', 'Date of Occurrence',
       'Time of Occurrence', 'City', 'Crime Code', 'Crime Description',
       'Victim Age', 'Victim Gender', 'Weapon Used', 'Crime Domain',
       'Police Deployed', 'Case Closed', 'Date Case Closed'],
      dtype='object')

In [7]:
df.shape

(40160, 14)

In [8]:
df.isnull().sum()

Report Number             0
Date Reported             0
Date of Occurrence        0
Time of Occurrence        0
City                      0
Crime Code                0
Crime Description         0
Victim Age                0
Victim Gender             0
Weapon Used            5790
Crime Domain              0
Police Deployed           0
Case Closed               0
Date Case Closed      20098
dtype: int64

In [9]:
date_columns = [
    'Date Reported',
    'Date of Occurrence',
    'Time of Occurrence',
    'Date Case Closed'
]
for col in date_columns:
    df[col] = pd.to_datetime(
        df[col],
        format='%d-%m-%Y %H:%M',
        errors='coerce'
    )

In [10]:
df['Report Number'].duplicated().sum()

np.int64(0)

In [11]:
df.duplicated().sum()

np.int64(0)

In [12]:
df['Weapon Used'] = df['Weapon Used'].fillna('Unknown')

In [13]:
pd.crosstab(
    df['Case Closed'],
    df['Date Case Closed'].isna()
)

Date Case Closed  False  True
Case Closed
No                    0  20098
Yes               20062      0

In [14]:
df['Year'] = df['Date of Occurrence'].dt.year

In [15]:
df['Month'] = df['Date of Occurrence'].dt.month

In [16]:
df['Month Name'] = df['Date of Occurrence'].dt.month_name()

In [17]:
df['Day of Week'] = df['Date of Occurrence'].dt.day_name()

In [18]:
df['Hour'] = df['Time of Occurrence'].dt.hour

In [20]:
def get_time_period(hour):
    if 5 <= hour < 12:
        return 'Morning'
    elif 12 <= hour < 17:
        return 'Afternoon'
    elif 17 <= hour < 21:
        return 'Evening'
    else:
        return 'Night'
df['Time Period'] = df['Hour'].apply(get_time_period)

In [21]:
df['Case Closure Days'] = (
    df['Date Case Closed'] - df['Date Reported']
).dt.total_seconds() / (24 * 60 * 60)

In [22]:
df['Victim Age'].describe()

count    40160.00000
mean        44.49126
std         20.22555
min         10.00000
25%         27.00000
50%         44.00000
75%         62.00000
max         79.00000
Name: Victim Age, dtype: float64

In [23]:
df[df['Victim Age'] < 0]

Empty DataFrame
Columns: [Report Number, Date Reported, Date of Occurrence, Time of Occurrence, City, Crime Code, Crime Description, Victim Age, Victim Gender, Weapon Used, Crime Domain, Police Deployed, Case Closed, Date Case Closed, Year, Month, Month Name, Day of Week, Hour, Time Period, Case Closure Days]
Index: []

[0 rows x 21 columns]

In [24]:
df[df['Victim Age'] > 100]

Empty DataFrame
Columns: [Report Number, Date Reported, Date of Occurrence, Time of Occurrence, City, Crime Code, Crime Description, Victim Age, Victim Gender, Weapon Used, Crime Domain, Police Deployed, Case Closed, Date Case Closed, Year, Month, Month Name, Day of Week, Hour, Time Period, Case Closure Days]
Index: []

[0 rows x 21 columns]

In [25]:
print(df['City'].unique())
print(df['Crime Description'].unique())
print(df['Victim Gender'].unique())
print(df['Weapon Used'].unique())
print(df['Crime Domain'].unique())
print(df['Case Closed'].unique())

['Ahmedabad' 'Chennai' 'Ludhiana' 'Pune' 'Delhi' 'Mumbai' 'Surat'
 'Visakhapatnam' 'Bangalore' 'Kolkata' 'Ghaziabad' 'Hyderabad' 'Jaipur'
 'Lucknow' 'Bhopal' 'Patna' 'Kanpur' 'Varanasi' 'Nagpur' 'Meerut' 'Thane'
 'Indore' 'Rajkot' 'Vasai' 'Agra' 'Kalyan' 'Nashik' 'Srinagar' 'Faridabad']
['IDENTITY THEFT' 'HOMICIDE' 'KIDNAPPING' 'BURGLARY' 'VANDALISM' 'ASSAULT'
 'VEHICLE - STOLEN' 'COUNTERFEITING' 'EXTORTION' 'PUBLIC INTOXICATION'
 'FRAUD' 'SEXUAL ASSAULT' 'DRUG OFFENSE' 'ARSON' 'CYBERCRIME'
 'TRAFFIC VIOLATION' 'SHOPLIFTING' 'ILLEGAL POSSESSION' 'FIREARM OFFENSE'
 'ROBBERY' 'DOMESTIC VIOLENCE']
['M' 'F' 'X']
['Blunt Object' 'Poison' 'Firearm' 'Other' 'Knife' 'Explosives' 'Unknown']
['Violent Crime' 'Other Crime' 'Fire Accident' 'Traffic Fatality']
['No' 'Yes']

In [26]:
df['Case Closed'].value_counts()

Case Closed
No     20098
Yes    20062
Name: count, dtype: int64

In [27]:
df.to_csv('crime_clean_data', index=False)

In [28]:
files.download('crime_clean_data')